<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BlockManager\Module'                        => __DIR__ . '/Module.php',
    'BlockManager\Controller\SkeletonController' => __DIR__ . '/src/BlockManager/Controller/SkeletonController.php',
    'BlockManagerTest\Framework\TestCase'        => __DIR__ . '/tests/BlockManager/Framework/TestCase.php',
    'BlockManagerTest\SampleTest'                => __DIR__ . '/tests/BlockManager/SampleTest.php',
);
